### ISSUE TITLE
getting 500 error after installation completed

### ISSUE THREAD

**Issue by ghost** [pixelandpen/docker-achecker#1]
any ideas here?  Not sure why this is failing in the apache2 error log i'm seeing this.

[Fri Aug 03 13:36:38.832691 2018] [:error] [pid 517] [client 172.x.x.x:21872] PHP Fatal error:  require_once(): Failed opening required 'include/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /app/include/vitals.inc.php on line 18

**Comment by pixelandpen** [comment]
Thanks for alerting me to this issue. I have rewritten the Dockerfile and added some needed scripts so that PHP7 and Composer are present for AChecker to install properly. Can you please confirm whether these changes fix the issue for you?
